include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_build_context_synchronously: false
    avoid_print: false
    unnecessary_brace_in_string_interps: false
    depend_on_referenced_packages: false
    prefer_null_aware_operators: false
    empty_catches: false
    no_leading_underscores_for_local_identifiers: false
