name: recapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  cached_network_image: ^3.2.3
  vibration: ^1.8.1
  share_plus: ^7.0.2
  uuid: ^4.2.1
  async: ^2.11.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  flutter_local_notifications: ^17.0.1

  #FIREBASE
  firebase_auth: ^4.17.6
  firebase_messaging: ^14.7.17
  cloud_firestore: ^4.15.6
  firebase_core: ^2.25.5

  flutter_riverpod: ^2.4.10

dev_dependencies:
  icons_launcher: ^2.1.7

  flutter_lints: ^2.0.0

icons_launcher:
  image_path: "assets/png/logo_green.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter_native_splash:
  color: "#4d8d6e"
  image: assets/png/logo_green.png

flutter:
  assets:
    - assets/png/
  uses-material-design: true
